name: pgdrome
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  # runtime
  - fenics=2019.1.0
  - numpy
  - scipy
  - h5py=3.3.0
  - hdf5=1.10.6
  # tests
  - pytest
  # formatting
  - black
  - pip
  - pip:
    - -e .
    - build
    - twine
