name: pgdrome
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8, <3.10
  # runtime
  - fenics=2019.1.0
  - numpy
  - scipy
  - h5py
  - hdf5
  # tests
  - pytest
  # formatting
  - black
  - pip
  - pip:
    - -e .
    - build
    - twine
