# This workflow will install the environment, run tests and check for code style and or large files (max kb=100)

name: Tests for pgdrome

on: [push]

jobs:
  # Run tests
  test_model:
    name: Run tests
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        channels: conda-forge
        channel-priority: strict
        auto-update-conda: true
        environment-file: environment.yml

    - name: Run tests
      shell: bash -l {0} #new shell
      run: |
        pytest

  # Style checking
  style_check:
    name: Style and file check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install pre-commit
      - name: Type check
        run: |
          pre-commit run --all-files --verbose --show-diff-on-failure
