# This workflow will install the enviroment and run tests

name: Tests for pgdrome

on: [push]

jobs:
  testing_tests:
    runs-on: [ubuntu-latest]

    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: latest

    - name: setup-conda-env
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment.yml
        mamba-version: "*"
        auto-update-conda: true
        activate-enviroment: pgdrome

    - name: Run tests
      shell: bash -l {0} #new shell
      run: |
        cd $GITHUB_WORKSPACE/tests/
        pytest -W error::UserWarning

