# This workflow will install the enviroment and run tests

name: Tests for pgdrome

on: [push]

jobs:
  test_model:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9.7
        mamba-version: "*"
        channels: conda-forge
        channel-priority: strict
        auto-update-conda: true
        environment-file: environment.yml

    - name: Run tests
      shell: bash -l {0} #new shell
      run: |
        python3 -m pip install .
        pytest

#name: Tests for pgdrome
#
#on: [push]
#
#jobs:
#  testing_tests:
#    runs-on: [ubuntu-latest]
#
#    steps:
#    - name: checkout repo
#      uses: actions/checkout@v2
#    - name: setup python
#      uses: actions/setup-python@v2
#      with:
#        python-version: 3.9 #>3.7
#
#    - name: setup-conda-env
#      uses: conda-incubator/setup-miniconda@v2
#      with:
#        environment-file: environment.yml
#        mamba-version: "*"
#        auto-update-conda: false
##        activate-enviroment: pgdrome
#
#    - name: Run tests
#      shell: bash -l {0} #new shell
#      run: |
#        python3 -m pip install .
#        pytest -W error::UserWarning

